defaults:
  - logger: logger
  - arch: anakin
  - system: ppo/rec_mappo
  - network: rnn # [rnn, rcnn]
  - env: glider_ma # [cleaner, connector, vector-connector, gigastep, lbf, mabrax, matrax, rware, smax, mpe]
  - _self_

logger:
  system_name: rec_mappo


hydra:
  searchpath:
    - file://mava/configs
